# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

updates:

  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "* * * * *"
    target-branch: ["main", "feature/python-eval", "dev"]
    labels:
      - "security-issues"
      - "python"
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 5
    versioning-strategy: lockfile-only
    security-updates-only: false
    commit-message:
      prefix: "fix(python)"
      include: "scope"
  # Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "* * * * *"
    target-branch: ["main", "feature/python-eval", "dev"]
    labels:
      - "security-issues"
      - "javascript"
    open-pull-requests-limit: 5
    versioning-strategy: lockfile-only
    security-updates-only: false
    commit-message:
      prefix: "fix(npm)"
      include: "scope"
